#pragma once

#include <winioctl.h>

#ifdef EDRAGENT_EXPORTS
#define EDRAGENT_EXPORT_API __declspec(dllexport) __stdcall  
#else
#define EDRAGENT_EXPORT_API __declspec(dllimport) __stdcall 
#endif

#ifdef __cplusplus
extern "C" {
#endif
	BOOL 
		EDRAGENT_EXPORT_API 
		InitDrv(int nType);
	BOOL 
		EDRAGENT_EXPORT_API 
		DeInitDrv(int nType);
	BOOL 
		EDRAGENT_EXPORT_API 
		SetFullList(int nType, char *szList, DWORD dwLen);
	BOOL 
		EDRAGENT_EXPORT_API 
		Clear(int nType);
	BOOL 
		EDRAGENT_EXPORT_API 
		Add(int nType, char *szList, DWORD dwLen);
	BOOL 
		EDRAGENT_EXPORT_API 
		Remove(int nType, char *szList, DWORD dwLen);

#ifdef __cplusplus
}
#endif
	
#define FILE_DEVICE_FILEMON			0x00008300
#define IOCTL_EDR_REGISTRY_INIT		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xB5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EDR_REGISTRY_DEINIT	(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xB6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EDR_REGISTRY_FULLLIST	(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xB7, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EDR_REGISTRY_CLEAR	(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xB8, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EDR_REGISTRY_ADD		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xB9, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EDR_REGISTRY_REMOVE	(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xBA, METHOD_BUFFERED, FILE_ANY_ACCESS)


#define IOCTL_EDR_FILE_INIT			(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EDR_FILE_DEINIT		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EDR_FILE_FULLLIST		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EDR_FILE_CLEAR		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EDR_FILE_ADD			(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EDR_FILE_REMOVE		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC5, METHOD_BUFFERED, FILE_ANY_ACCESS)


#define FILE_DEVICE_TDI_FW_NFO		0x8e87
#define TDI_EDR_IOCTL_INDEX			0xA10
#define IOCTL_TDI_CMD_INIT			CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TDI_CMD_DEINIT		CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TDI_CMD_FULLLIST		CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TDI_CMD_CLEAR			CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TDI_CMD_ADD			CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TDI_CMD_REMOVE		CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 5, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define FILE_DEVICE_SAFEFW			0x9000
#define SAFEFW_EDR_IOCTL_INDEX		0x950
#define IOCTL_SAFEFW_CMD_INIT		CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SAFEFW_CMD_DEINIT		CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SAFEFW_CMD_FULLLIST	CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SAFEFW_CMD_CLEAR		CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SAFEFW_CMD_ADD		CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SAFEFW_CMD_REMOVE		CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 5, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef enum _EdrType
{
	EDR_TYPE_PROCESS = 0,
	EDR_TYPE_FILE,
	EDR_TYPE_IP,
	EDR_TYPE_URL,
	EDR_TYPE_REG
} EEDRType;



