#ifndef __CONTROLS_H__
#define __CONTROLS_H__

#define	EProcessCreate	0x00000001
#define	EProcessDelete	0x00000010
#define	EProcessBoth	(EProcessCreate|EProcessCreate)


#define IOCTL_REGISTER_EVENT \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_REGISTER_EVENT_FOR_DELETE \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_GET_PROCESS_COUNT \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_GET_PROCESS_LIST \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_TERMINATE_ALL \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_ALLOW \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_BLOCK \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_RESET \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_DELETE_COMPLETED \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x809, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_GET_INIT_COUNT \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x810, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_GET_INIT_PROCESS \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x811, METHOD_BUFFERED, FILE_READ_ACCESS)

#endif // __CONTROLS_H__
