#pragma once
#ifndef _EDRAGENT_DLL_H_
#define _EDRAGENT_DLL_H_

#include <winioctl.h>

typedef enum _EEDRType
{
	EDR_TYPE_INVALID = -1,
	EDR_TYPE_PROCESS = 0,
	EDR_TYPE_FILE,
	EDR_TYPE_IP,
	EDR_TYPE_URL,
	EDR_TYPE_REG,
	EDR_TYPE_MAX,
} EEDRType;

typedef enum _EIOCTLCode
{
	EIOCTL_INVALID = -1,
	EIOCTL_INIT = 0,
	EIOCTL_DEINIT,
	EIOCTL_SETFULLLIST,
	EIOCTL_CLEAR,
	EIOCTL_ADD,
	EIOCTL_REMOVE,
	EIOCTL_SETEVENT,
	EIOCTL_GETLOGSIZE,
	EIOCTL_GETLOG,
	EIOCTL_MAX,
} EIOCTLCode;

typedef struct _EDROpt_T
{
	DWORD    	dwLogBufferCount;
	BOOLEAN		bNeedConvertUnicode;

	DWORD    	dwMaxBuffSize;
	DWORD   	dwMaxTrhSize;
	DWORD		dwUsePolling;
	DWORD   	reserved_3;
	DWORD    	reserved_4;
	DWORD   	reserved_5;
	DWORD    	reserved_6;
	DWORD    	reserved_7;
	DWORD    	reserved_8;
} EDROpt;

#ifdef EDRAGENT_EXPORTS
#define EDRAGENT_EXPORT_API __declspec(dllexport) __stdcall  
#else
#define EDRAGENT_EXPORT_API __declspec(dllimport) __stdcall 
#endif

namespace SafePCKModule
{
#ifdef __cplusplus
	extern "C" {
#endif
		BOOL
			EDRAGENT_EXPORT_API
			InitDrv(INT nType);
		BOOL
			EDRAGENT_EXPORT_API
			DeInitDrv(INT nType);
		BOOL
			EDRAGENT_EXPORT_API
			SetFullList(INT nType, CHAR* inBuf, DWORD outLen);
		BOOL
			EDRAGENT_EXPORT_API
			Clear(INT nType);
		BOOL
			EDRAGENT_EXPORT_API
			Add(INT nType, CHAR* inBuf, DWORD outLen);
		BOOL
			EDRAGENT_EXPORT_API
			Remove(INT nType, CHAR* inBuf, DWORD outLen);
		BOOL
			EDRAGENT_EXPORT_API
			InitEvent(INT nType, HANDLE* outBuf, DWORD outLen);
		BOOL
			EDRAGENT_EXPORT_API
			GetLogSize(INT nType, ULONG* outBuf, DWORD outLen);
		BOOL
			EDRAGENT_EXPORT_API
			GetLog(INT nType, CHAR* outBuf, DWORD outLen);

#ifdef __cplusplus
	}
#endif

	#define IOCTL_INVALID					0

	#define FILE_DEVICE_FILEMON				0x00008300
	#define IOCTL_EDR_REGISTRY_INIT			(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xB5, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_REGISTRY_DEINIT		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xB6, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_REGISTRY_FULLLIST		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xB7, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_REGISTRY_CLEAR		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xB8, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_REGISTRY_ADD			(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xB9, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_REGISTRY_REMOVE		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xBA, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_REGISTRY_INITEVENT	(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xBB, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_REGISTRY_GETLOGSIZE	(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xBC, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_REGISTRY_GETLOG		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xBD, METHOD_BUFFERED, FILE_ANY_ACCESS)


	#define IOCTL_EDR_FILE_INIT				(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC0, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_FILE_DEINIT			(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC1, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_FILE_FULLLIST			(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC2, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_FILE_CLEAR			(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC3, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_FILE_ADD				(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC4, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_FILE_REMOVE			(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC5, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_FILE_INITEVENT		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC6, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_FILE_GETLOGSIZE		(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC7, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_EDR_FILE_GETLOG			(ULONG) CTL_CODE(FILE_DEVICE_FILEMON, 0xC8, METHOD_BUFFERED, FILE_ANY_ACCESS)

	#define FILE_DEVICE_TDI_FW_NFO			0x8e87
	#define TDI_EDR_IOCTL_INDEX				0xA20
	#define IOCTL_TDI_CMD_INIT				(ULONG)CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_TDI_CMD_DEINIT			(ULONG)CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_TDI_CMD_FULLLIST			(ULONG)CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_TDI_CMD_CLEAR				(ULONG)CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_TDI_CMD_ADD				(ULONG)CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_TDI_CMD_REMOVE			(ULONG)CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 5, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_TDI_CMD_INITEVENT			(ULONG)CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_TDI_CMD_GETLOGSIZE		(ULONG)CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 7, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_TDI_CMD_GETLOG			(ULONG)CTL_CODE(FILE_DEVICE_TDI_FW_NFO, TDI_EDR_IOCTL_INDEX + 8, METHOD_BUFFERED, FILE_ANY_ACCESS)

	#define FILE_DEVICE_SAFEFW				0x9000
	#define SAFEFW_EDR_IOCTL_INDEX			0x950
	#define IOCTL_SAFEFW_CMD_INIT			(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_CMD_DEINIT			(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_CMD_FULLLIST		(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_CMD_CLEAR			(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_CMD_ADD			(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_CMD_REMOVE			(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 5, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_CMD_INITEVENT		(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 10, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_CMD_GETLOGSIZE		(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 11, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_CMD_GETLOG			(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 12, METHOD_BUFFERED, FILE_ANY_ACCESS)
										
	#define IOCTL_SAFEFW_URL_FULLLIST		(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_URL_CLEAR			(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 7, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_URL_ADD			(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 8, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_URL_REMOVE			(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 9, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_URL_INITEVENT		(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 13, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_URL_GETLOGSIZE		(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 14, METHOD_BUFFERED, FILE_ANY_ACCESS)
	#define IOCTL_SAFEFW_URL_GETLOG			(ULONG)CTL_CODE(FILE_DEVICE_SAFEFW, SAFEFW_EDR_IOCTL_INDEX + 15, METHOD_BUFFERED, FILE_ANY_ACCESS)
}

#endif